[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["cd ../.. && pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["cd ../.. && pnpm --filter @lovecoin/web run build"]

[start]
cmd = "pnpm start"
