[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["cd ../.. && pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["cd ../.. && pnpm --filter @lovecoin/api run db:generate && pnpm --filter @lovecoin/api run build"]

[start]
cmd = "npx prisma db push --skip-generate && node dist/index.js"
